server:
  port: ${PORT:8081}

spring:
  application:
    name: ${NAME_APP:rs-client}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://192.168.66.30:3306/store
    username: root
    password: devops@integra 
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL1:http://localhost:8761/eureka/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
  info:
    build:
      enabled: true
    