server:
  port: ${PORT:8086}

spring:
  application:
    name: ${NAME_APP:spec-client} 
store: 
  url:
    rs-client: ${URL_RS_CLIENT:}
  
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL1:http://localhost:8761/eureka/eureka}
  instance:
    prefer-ip-address: true